eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.161:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8081
spring:
  application:
    name: service-provider
  zipkin:
    base-url: http://192.168.1.161:9411
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS