spring:
  application:
    name: newbie-apollo-configservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003171
  
server:
  port: 8767

logging:
  file: /opt/logs/100003171/apollo-configservice.log
